print("Hola mundo")
print("Hola mundo d")
print("Hola mundo x")
print("Hola mundo z")
print("Hola mundo y")
print("Hola mundo 4")
print("Hola mundo 5")
print("Hola mundo 5345")
print("Hola mundo 545")
print("Hola mundo 45")